"""
╔══════════════════════════════════════════════════════════════════════════════╗
║  ROSIE WORKER v2.0 — Integration Layer                                       ║
║                                                                              ║
║  Reads the clean CEAP CSV from /data/ceap (Generated by ExpensesWorker)      ║
║  runs all 12 Rosie classifiers, and pushes anomaly findings to the Backend.  ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""

import sys
import os
import csv
import json
import logging
import argparse
import requests
from pathlib import Path
from collections import defaultdict
from datetime import datetime
from typing import List, Dict, Optional
from src.gatherers.rosie_engine import RosieEngine

sys.path.append(str(Path(__file__).resolve().parent.parent.parent.parent))

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger("rosie_worker")


# =============================================================================
# BLACKLIST LOADER (Portal da Transparência CEIS/CNEP)
# =============================================================================
class BlacklistLoader:
    PORTAL_API = "https://api.portaldatransparencia.gov.br/api-de-dados"

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("PORTAL_API_KEY", "")
        self.blacklisted_cnpjs: set = set()

    def load(self) -> set:
        if not self.api_key:
            logger.warning("[BlacklistLoader] No PORTAL_API_KEY. Skipping CEIS/CNEP download.")
            return self._load_from_cache()

        headers = {"chave-api-dados": self.api_key, "Accept": "application/json"}

        for endpoint, name in [("ceis", "CEIS"), ("cnep", "CNEP")]:
            try:
                logger.info(f"[BlacklistLoader] Downloading {name}...")
                page = 1
                while page <= 20:
                    resp = requests.get(
                        f"{self.PORTAL_API}/{endpoint}",
                        headers=headers,
                        params={"pagina": page},
                        timeout=30,
                    )
                    if resp.status_code != 200:
                        break
                    data = resp.json()
                    if not data:
                        break

                    for entry in data:
                        cnpj = (
                            entry.get("cnpjSancionado", "") or
                            entry.get("pessoaJuridica", {}).get("cnpjFormatado", "") or
                            ""
                        )
                        cnpj_clean = cnpj.replace(".", "").replace("/", "").replace("-", "").strip()
                        if cnpj_clean and len(cnpj_clean) >= 11:
                            self.blacklisted_cnpjs.add(cnpj_clean)
                    page += 1

                logger.info(f"  {name}: loaded (total blacklist: {len(self.blacklisted_cnpjs)})")
            except Exception as e:
                logger.error(f"  Error loading {name}: {e}")

        self._save_cache()
        return self.blacklisted_cnpjs

    def _cache_path(self) -> Path:
        return Path(__file__).resolve().parent.parent.parent.parent / "data" / "processed" / "blacklist_cache.json"

    def _save_cache(self):
        try:
            path = self._cache_path()
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, "w") as f:
                json.dump(list(self.blacklisted_cnpjs), f)
        except Exception:
            pass

    def _load_from_cache(self) -> set:
        try:
            path = self._cache_path()
            if path.exists():
                with open(path, "r") as f:
                    data = json.load(f)
                self.blacklisted_cnpjs = set(data)
        except Exception:
            pass
        return self.blacklisted_cnpjs


# =============================================================================
# MAIN ROSIE WORKER
# =============================================================================
class RosieWorker:
    ALL_CATEGORIES = True

    def __init__(self, years: List[int] = None, backend_url: str = "http://localhost:8080"):
        self.years = years or [2024, 2025]
        self.backend_url = backend_url

    def _download_and_parse_full(self, year: int, target_ids: Optional[set] = None) -> List[Dict]:
        """
        Lê o CSV Local fixado pelo ExpensesWorker e gera a lista de recibos.
        Filtro de ID impermeável via string comparison.
        """
        csv_path = Path(__file__).resolve().parent.parent.parent.parent / "data" / "ceap" / f"ceap_{year}.csv"
        
        logger.info(f"📥 Loading CEAP {year} for Rosie analysis from CSV Cache...")

        if not csv_path.exists():
            logger.error(f"  ❌ CSV {csv_path} não encontrado! Corra o ExpensesWorker primeiro.")
            return []

        csv.field_size_limit(1024 ** 2)
        receipts = []
        skipped = 0
        
        # Converte os alvos para strings puras (ex: "204379")
        safe_target_ids = {str(tid).strip() for tid in target_ids} if target_ids else None

        with open(csv_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f, delimiter=";")
            
            for row in reader:
                row_lower = {k.lower(): v for k, v in row.items() if k}

                dep_id_str = row_lower.get("idecadastro", "") or row_lower.get("idcadastro", "")
                dep_id_str = dep_id_str.strip()
                
                if not dep_id_str.isdigit():
                    skipped += 1
                    continue

                # Filtro Impermeável em String! 
                if safe_target_ids and dep_id_str not in safe_target_ids:
                    continue

                dep_id = int(dep_id_str)

                try:
                    valor = float(row_lower.get("vlrliquido", "0").replace(",", "."))
                except ValueError:
                    valor = 0.0

                if valor <= 0:
                    continue

                data_doc = row_lower.get("datemissao", "")
                if data_doc and "T" in data_doc:
                    data_doc = data_doc.split("T")[0]
                elif data_doc and " " in data_doc:
                    data_doc = data_doc.split(" ")[0]

                receipt = {
                    "id": f"ceap_{year}_{row_lower.get('numdocumento', '')}_{dep_id}_{abs(hash(row_lower.get('txtfornecedor', '')))}",
                    "deputy_id": str(dep_id),
                    "deputy_name": row_lower.get("txnomeparlamentar", "").strip(),
                    "party": row_lower.get("sgpartido", "").strip(),
                    "ufDeputado": row_lower.get("sguf", "").strip(),
                    "dataEmissao": data_doc[:10] if data_doc else "",
                    "categoria": row_lower.get("txtdescricao", "").strip(),
                    "subcategoria": row_lower.get("txtdescricaoespecificacao", "").strip(),
                    "valorDocumento": valor,
                    "valorGlosa": float(row_lower.get("vlrglosa", "0").replace(",", ".") or "0"),
                    "nomeFornecedor": row_lower.get("txtfornecedor", "").strip(),
                    "cnpjFornecedor": row_lower.get("txtcnpjcpf", "").strip(),
                    "ufFornecedor": row_lower.get("sguf", "NA"), 
                    "numDocumento": row_lower.get("numdocumento", "").strip(),
                    "numLote": row_lower.get("numlote", "").strip(),
                    "numParcela": row_lower.get("numparcela", "").strip(),
                    "year": year,
                }
                receipts.append(receipt)

        logger.info(f"  ✅ Parsed {len(receipts)} valid receipts (skipped {skipped} invalid rows)")
        return receipts

    def _fetch_deputy_ids(self, limit: int) -> set:
        try:
            all_ids = set()
            page = 1
            while True:
                resp = requests.get(
                    "https://dadosabertos.camara.leg.br/api/v2/deputados",
                    params={"pagina": page, "itens": 100, "ordem": "ASC", "ordenarPor": "nome"},
                    timeout=30,
                )
                if resp.status_code != 200: break
                data = resp.json()
                if not data.get("dados"): break
                for d in data["dados"]:
                    all_ids.add(d["id"])
                if not any(l.get("rel") == "next" for l in data.get("links", [])):
                    break
                page += 1
            return set(sorted(all_ids)[:limit]) if limit else all_ids
        except Exception as e:
            logger.error(f"  Failed to fetch deputy IDs: {e}")
            return set()

    def _push_anomalies_to_backend(self, report: Dict):
        try:
            for dep_id, scores in report.get("deputy_risk_scores", {}).items():
                external_id = f"camara_{dep_id}"
                payload = {
                    "externalId": external_id,
                    "rosieRiskScore": scores["risk_score"],
                    "rosieAnomalies": scores["n_anomalies"],
                    "rosieClassifiersTriggered": scores["n_classifiers_triggered"],
                    "rosieTopFindings": [
                        {
                            "classifier": a["classifier"],
                            "confidence": a["confidence"],
                            "reason": a["reason"],
                        }
                        for a in scores.get("top_anomalies", [])[:5]
                    ],
                }
                resp = requests.post(f"{self.backend_url}/api/internal/workers/ingest/rosie-score", json=payload, timeout=10)
        except Exception as e:
            pass

    def _save_report(self, report: Dict, all_receipts: List[Dict]):
        """Save individual Rosie reports per deputy with their names."""
        try:
            reports_dir = Path(__file__).resolve().parent.parent.parent.parent / "data" / "processed" / "rosie_reports"
            reports_dir.mkdir(parents=True, exist_ok=True)

            id_to_name = {}
            for r in all_receipts:
                dep_id = str(r.get("deputy_id", ""))
                dep_name = r.get("deputy_name", "").strip()
                if dep_id and dep_name:
                    id_to_name[dep_id] = dep_name

            for dep_id, scores in report.get("deputy_risk_scores", {}).items():
                dep_name = id_to_name.get(str(dep_id), "Desconhecido")
                safe_name = dep_name.replace(" ", "_").lower()
                
                deputy_anomalies = [a for a in report.get("all_anomalies", []) if str(a.get("deputy_id")) == str(dep_id)]
                
                dep_report = {
                    "deputado_nome": dep_name,
                    "deputado_id": dep_id,
                    "risco_score": scores.get("risk_score", 0),
                    "total_anomalias": scores.get("n_anomalies", 0),
                    "classificadores_acionados": scores.get("n_classifiers_triggered", 0),
                    "principais_anomalias": scores.get("top_anomalies", []),
                    "todas_anomalias_detalhadas": deputy_anomalies
                }
                
                filename = f"rosie_report_{safe_name}_{dep_id}.json"
                filepath = reports_dir / filename
                with open(filepath, "w", encoding="utf-8") as f:
                    json.dump(dep_report, f, ensure_ascii=False, indent=2, default=str)

            base_path = Path(__file__).resolve().parent.parent.parent.parent / "data" / "processed"
            global_path = base_path / "rosie_report_summary.json"
            with open(global_path, "w", encoding="utf-8") as f:
                json.dump(report.get("summary", {}), f, ensure_ascii=False, indent=2, default=str)
        except Exception as e:
            logger.error(f"  Failed to save report: {e}")

    def _save_anomalies_csv(self, report: Dict, filename: str = "rosie_anomalies.csv"):
        try:
            base_path = Path(__file__).resolve().parent.parent.parent.parent / "data" / "processed"
            base_path.mkdir(parents=True, exist_ok=True)

            filepath = base_path / filename
            anomalies = report.get("all_anomalies", [])
            if not anomalies: return None

            fieldnames = ["deputy_id", "receipt_id", "classifier", "confidence", "reason"]
            with open(filepath, "w", newline="", encoding="utf-8") as f:
                writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
                writer.writeheader()
                for a in anomalies:
                    writer.writerow({
                        "deputy_id": a.get("deputy_id", ""),
                        "receipt_id": a.get("receipt_id", ""),
                        "classifier": a.get("classifier", ""),
                        "confidence": a.get("confidence", 0),
                        "reason": a.get("reason", ""),
                    })
        except Exception as e:
            pass

    def run(self, limit: int = 100):
        logger.info("╔══════════════════════════════════════════════════════════╗")
        logger.info("║  🤖 ROSIE WORKER v2.0 — Full Anomaly Detection         ║")
        logger.info("╚══════════════════════════════════════════════════════════╝")
        start_time = datetime.now()

        bl = BlacklistLoader()
        blacklist = bl.load()

        target_ids = self._fetch_deputy_ids(limit)
        logger.info(f"  Found {len(target_ids)} deputies")

        all_receipts = []
        for year in self.years:
            receipts = self._download_and_parse_full(year, target_ids)
            all_receipts.extend(receipts)

        if not all_receipts:
            logger.error("  ❌ No receipts found. Aborting.")
            return

        logger.info("\n🤖 Step 4: Running Rosie Engine...")
        rosie = RosieEngine(blacklist_cnpjs=blacklist, company_dates=None, enable_all=True)
        report = rosie.analyze(all_receipts)

        logger.info("\n📤 Step 5: Pushing results to backend...")
        self._push_anomalies_to_backend(report)

        logger.info("\n💾 Step 6: Saving reports...")
        self._save_report(report, all_receipts)
        self._save_anomalies_csv(report, "rosie_anomalies.csv")

        elapsed = (datetime.now() - start_time).total_seconds()
        logger.info(f"\n{'='*60}")
        logger.info(f"  🤖 ROSIE WORKER COMPLETE — {elapsed:.1f}s")
        logger.info(f"  Receipts analyzed: {len(all_receipts)}")
        logger.info(f"  Anomalies found:   {report['summary']['total_anomalies']}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Rosie Worker (Native CSV)")
    parser.add_argument("--limit", type=int, default=50)
    parser.add_argument("--years", type=int, nargs="+", default=[2024, 2025])
    args = parser.parse_args()

    worker = RosieWorker(years=args.years)
    worker.run(limit=args.limit)