package com.tp360.core.domain;

import jakarta.persistence.*;
import java.time.LocalDate;

@Entity
@Table(name = "votes")
public class Vote {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "politician_id", nullable = false)
    private Politician politician;

    @Column(nullable = false)
    private String propositionExternalId; // ID of the bill/law being voted on

    private String propositionSummary;

    @Column(nullable = false)
    private String voteChoice; // "Sim", "Não", "Abstenção"

    private LocalDate voteDate;

    // Link generated by Cross-Reference Worker regarding Coherence
    private Double coherenceScore; // from -1.0 to 1.0 comparing to promises
    @Column(columnDefinition = "TEXT")
    private String coherenceExplanation; // LLM output

    // Accessors
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public Politician getPolitician() { return politician; }
    public void setPolitician(Politician politician) { this.politician = politician; }
    public String getPropositionExternalId() { return propositionExternalId; }
    public void setPropositionExternalId(String propositionExternalId) { this.propositionExternalId = propositionExternalId; }
    public String getPropositionSummary() { return propositionSummary; }
    public void setPropositionSummary(String propositionSummary) { this.propositionSummary = propositionSummary; }
    public String getVoteChoice() { return voteChoice; }
    public void setVoteChoice(String voteChoice) { this.voteChoice = voteChoice; }
    public LocalDate getVoteDate() { return voteDate; }
    public void setVoteDate(LocalDate voteDate) { this.voteDate = voteDate; }
    public Double getCoherenceScore() { return coherenceScore; }
    public void setCoherenceScore(Double coherenceScore) { this.coherenceScore = coherenceScore; }
    public String getCoherenceExplanation() { return coherenceExplanation; }
    public void setCoherenceExplanation(String coherenceExplanation) { this.coherenceExplanation = coherenceExplanation; }
}
